# Need sudo user permission to execute this build
sudo: required
language: generic

services : 
  - docker

before_install:
  - docker build -t imvipul26/docker-react -f dockerfile.dev .

script:
  - docker run imvipul26/docker-react npm run test -- --coverage
