# Need sudo user permission to execute this build
sudo: required
language: generic

services : 
  - docker

before_install:
  - docker build -t imvipul26/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true imvipul26/docker-react npm run test -- --coverage

deploy:
  provider: elastibeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-038109337046"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key
